# ===============================================
# Docker Compose for Jira Project Assistant
# ===============================================

version: '3.9'

services:
  # Main UI application service
  ui:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
      # Build arguments (if needed)
      args:
        NODE_ENV: production

    # Container name for easier management
    container_name: jira-assistant-ui

    # Port mapping: host:container
    ports:
      - "8080:80"

    # Environment variables
    environment:
      - NODE_ENV=production
      - TZ=UTC

    # Restart policy
    restart: unless-stopped

    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

    # Resource limits (optional, adjust as needed)
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M

    # Labels for documentation and management
    labels:
      - "com.docker.compose.project=jira-assistant"
      - "com.docker.compose.service=ui"
      - "traefik.enable=false"  # Disable if using Traefik
      - "maintainer=Alex_Tol"
      - "version=1.0.0"

    # Volumes (if needed for logs or data)
    volumes:
    # Optional: Custom nginx config override
    # - ./nginx.conf:/etc/nginx/nginx.conf:ro
    # Optional: Logs volume
    # - nginx-logs:/var/log/nginx

    # Networks
    networks:
      - jira-assistant-network

    # Dependencies (if we add more services later)
    # depends_on:
    #   - api

  # ===============================================
  # Optional: Development service with live reload
  # ===============================================
  ui-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: build  # Use only the build stage for development
    container_name: jira-assistant-dev
    ports:
      - "3000:3000"  # Vite dev server port
    environment:
      - NODE_ENV=development
    volumes:
      # Mount source code for live reload
      - ./static/ui/src:/app/static/ui/src
      - ./static/ui/public:/app/static/ui/public
      - ./static/ui/package.json:/app/static/ui/package.json
      - ./static/ui/vite.config.js:/app/static/ui/vite.config.js
      - ./static/ui/tsconfig.json:/app/static/ui/tsconfig.json
    command: npm run dev -- --host 0.0.0.0
    networks:
      - jira-assistant-network
    profiles:
      - development  # Only start with --profile development

# ===============================================
# Networks configuration
# ===============================================
networks:
  jira-assistant-network:
    driver: bridge
    name: jira-assistant-net

# ===============================================
# Volumes configuration (if needed)
# ===============================================
volumes:
  nginx-logs:
    name: jira-assistant-logs
  # node-modules:
  #   name: jira-assistant-node-modules

# ===============================================
# Usage Examples:
# ===============================================
#
# Production mode (default):
#   docker-compose up --build
#   docker-compose up -d  # Run in background
#
# Development mode with live reload:
#   docker-compose --profile development up ui-dev
#
# View logs:
#   docker-compose logs -f ui
#
# Stop and remove:
#   docker-compose down
#
# Full cleanup (remove images and volumes):
#   docker-compose down --rmi all --volumes
#
# Scale service (if needed):
#   docker-compose up --scale ui=3
#
# Health check:
#   curl http://localhost:8080/health
#
# Access application:
#   http://localhost:8080
#
# ===============================================
