version: '3.9'

services:
  # Production build с dev режимом (для тестирования)
  ui:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
      args:
        NODE_ENV: production
        VITE_DEV_MODE: "true"  # ВАЖНО: включаем dev режим для Docker

    container_name: jira-assistant-ui
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
      - TZ=UTC
    restart: unless-stopped
    networks:
      - jira-assistant-network

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

    labels:
      - "com.docker.compose.project=jira-assistant"
      - "com.docker.compose.service=ui"
      - "maintainer=Alex_Tol"
      - "version=1.0.0"

  # Development режим с live reload
  ui-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: jira-assistant-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - VITE_DEV_MODE=true
    volumes:
      - ./static/ui/src:/app/static/ui/src
      - ./static/ui/public:/app/static/ui/public
      - ./static/ui/package.json:/app/static/ui/package.json
      - ./static/ui/vite.config.js:/app/static/ui/vite.config.js
      - ./static/ui/tsconfig.json:/app/static/ui/tsconfig.json
    networks:
      - jira-assistant-network
    profiles:
      - development

networks:
  jira-assistant-network:
    driver: bridge
    name: jira-assistant-net
